repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.15.0'
    hooks:
      - id: eslint
        additional_dependencies: ['eslint@8.15.0', 'eslint-plugin-vue@8.7.1']
        args: ['--fix']
        files: '\.(js|vue)$'
        exclude: 'node_modules'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@2.7.1']
        args: ['--write']
        files: '\.(js|vue|css|scss|json|md)$'
        exclude: 'node_modules'
